# Generated by Django 5.0.1 on 2024-03-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineeducation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='message',
            field=models.BigIntegerField(),
        ),
    ]
