# Generated by Django 5.0.1 on 2024-03-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineeducation', '0004_post_like_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
