# Generated by Django 5.0.1 on 2024-03-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineeducation', '0005_remove_like_post_remove_like_user_remove_post_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField(unique=True)),
                ('video_url', models.CharField(max_length=255)),
            ],
        ),
    ]
